#!/bin/bash
[[ $(screen -list| grep -c 'bot_gen') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     BOT GENERATOR ACTIVATION     \E[0m"
    echo ""
    echo -ne "\033[1;32mENTER THE TOKEN\033[1;37m: "; read token
    echo ""
    echo -ne "\033[1;32mENTER YOUR ID\033[1;37m: "; read idtelegram
 echo ""
    echo -ne "\033[1;32mSERVER NAME\033[1;37m: "; read idserver
    cd /etc/VPSManager
    screen -dmS bot_gen ./botgerador $token $idtelegram $idserver> /dev/null 2>&1
    [[ $(grep -wc "bot_gen" /etc/autostart) = '0' ]] && {
                echo -e "ps x | grep 'bot_gen' | grep -v 'grep' || cd /etc/VPSManager && sudo screen -dmS bot_gen ./botgerador $token $idtelegram $idserver && cd $HOME" >>/etc/autostart
            } || {
                sed -i '/bot_gen/d' /etc/autostart
                echo -e "ps x | grep 'bot_gen' | grep -v 'grep' || cd /etc/VPSManager && sudo screen -dmS bot_gen ./botgerador $token $idtelegram $idserver && cd $HOME" >>/etc/autostart
            }  
    clear && echo "BOT ACTIVATED"
} || {
    screen -r -S "bot_gen" -X quit
    clear && echo "BOT DEACTIVATED"
}